### PR TITLE
Added advanced methods

### PR DESCRIPTION
**Pull request by guillaumecherel**

### CODE REVIEW

**Comment by jopasserat** [comment]
Beyond a market place contribution, this would suit nicely in the tutorial section of the website.
Would you consider translating your document into English?

**Comment by guillaumecherel** [comment]
I agree and we talked about it with Mathieu. But I'm not going to work 
on the translation anytime soon. Anyone else willing to work on it would 
be welcome.

**Comment by mathieuleclaire** [comment]
You should ask this question on the mailing list Guillaume. But I think, we can accept this nice request it in the meantime.

**Comment by romainreuillon** [comment]
It is a great contribution and I think this is totally worth it to merge it into the market in order to keep track of it, but we should not expose it in the application market until it is translated. This would look really messy to have some parts of the application in french or german or chinese...

Romain

**Comment by mathieuleclaire** [comment]
I agree. I will start with translating it. Peharps we could propose a collaborative translation through the mailing list (if we 3 our 4, it can be achieved shortly).

**Comment by romainreuillon** [comment]
:+1:

**Pull request merged**
