### PR TITLE
Minor README typos.

### PR DESCRIPTION
**Pull request by merriam**
Just a 'drive-by edit' making small improvements.

### CODE REVIEW

**Comment by mathieuleclaire** [comment]
Hi Merriam, thanks for your contribution ! Could it be possible to push this in the master branch ? 

We use 2 branches: the dev one for the new developments and master to maintains the current version. We have to fix the website page describing this.

**Comment by romainreuillon** [comment]
I just created the master branch. This PR should be merged against this branch so it can be merged to 7-dev and 8-dev.

**Comment by romainreuillon** [comment]
Actually I think it may work like that since the branch didn't diverge too much.

**Comment by romainreuillon** [comment]
This patch has been integrated to branches 7-dev, 8-dev and master.

**Pull request merged**
